#!/usr/bin/env python3
"""
Generic force terms: Coriolis-centripetal coupling, and wind.

Nothing here knows what shape the hull is. Everything takes a mass matrix or a
set of areas and coefficients, so the same code serves a Wigley test hull, a
mesh imported from a real vessel, or anything else -- which is the point, since
the model has to accept the real USV's data later.

CORIOLIS

`sim/vessel.py` carried two of the six rigid-body components and none of the
added-mass ones. Rather than write the missing terms out by hand -- which is how
sign errors get in -- both are built from one construction that is correct by
structure:

    C(nu) = [[      0,        -S(A11 v1 + A12 v2) ],
             [ -S(A11 v1 + A12 v2),  -S(A21 v1 + A22 v2) ]]

with A the 6x6 mass matrix partitioned into 3x3 blocks, v1 = [u,v,w],
v2 = [p,q,r], and S(a) the cross-product matrix. Two properties make this the
right thing to write:

  it is SKEW-SYMMETRIC, so nu . C(nu) nu = 0 identically. Coriolis forces do no
  work, and here that is guaranteed by the shape of the matrix rather than by
  the terms happening to cancel. `test_skew` checks it numerically anyway.

  it reduces to the textbook result. For the rigid body with the centre of
  gravity at the origin it gives m (omega x v) in the force rows and
  omega x (I omega) in the moment rows -- which is Euler's equation, derived
  rather than recalled.

WHICH FRAME -- the part the checks below cannot see

Both properties are properties of the ALGEBRA. Neither says whether the model
using the matrix is written in a body-fixed frame, and that decides which terms
exist. `sim/vessel.py` rotates only the horizontal velocities by heading and
integrates heave, roll and pitch rates directly -- a manoeuvring frame in the
horizontal plane, a seakeeping frame for the oscillatory modes -- so there the
frame rotates in yaw alone and the vessel passes nu with w, p, q zeroed. Feeding
it the full nu was tried: it passed both checks and put 6 kN rms of spurious
force into heave (DEFECTS E11).

The same construction applied to the infinite-frequency added mass gives the
added-mass Coriolis force. That one matters here as much as the rigid-body part,
because A_inf is comparable with M for a small hull.

WIND

Absent entirely before this, in all three horizontal degrees of freedom, on a
vessel whose sea state is BY DEFINITION generated by wind. The force uses
APPARENT wind -- true wind minus the vessel's own velocity -- because a vessel
making 4.5 m/s into an 11 m/s breeze feels 15.5, and the difference is a factor
of two in force.

The angular shapes are the standard trigonometric forms used when measured
coefficient curves are not available:

    C_X(g) = cx * cos(g)         C_Y(g) = cy * sin(g)         N = Y * x_wind

with g the apparent wind angle in the body frame. They have the right symmetry
and the right zeros, and the signs follow the physics rather than a convention:
the force points along the apparent wind. The yaw moment is written as the side
force acting at a LEVER rather than as a C_N coefficient, because a lever can be
read off a profile drawing and its sign decides whether the vessel weathervanes
into the wind or away from it.

The amplitudes cx, cy and the lever are placeholders of the same standing as the
viscous damping. Blendermann and Isherwood published measured coefficient sets
from wind-tunnel tests, and those are what belongs here -- including the real
C_N(g) shape, which peaks nearer 40 degrees than 90 and is therefore not exactly
a constant lever. Flagged in CALIBRATION_NEEDED.
"""
import numpy as np

RHO_AIR = 1.225

CALIBRATION_NEEDED = [
    "wind force coefficients cx, cy and the yaw lever x_wind (needs "
    "Blendermann or Isherwood coefficient sets, or a wind-tunnel test)",
]


def skew(a):
    """Cross-product matrix: skew(a) @ b == np.cross(a, b)."""
    return np.array([[0.0, -a[2], a[1]],
                     [a[2], 0.0, -a[0]],
                     [-a[1], a[0], 0.0]])


def coriolis_matrix(M, nu):
    """Coriolis-centripetal matrix for a 6x6 mass matrix `M` at velocity `nu`.

    Works for the rigid-body inertia and for the added mass alike -- they are
    the same algebra on different matrices.
    """
    v1, v2 = np.asarray(nu[:3], float), np.asarray(nu[3:], float)
    top = M[:3, :3] @ v1 + M[:3, 3:] @ v2
    bot = M[3:, :3] @ v1 + M[3:, 3:] @ v2
    C = np.zeros((6, 6))
    C[:3, 3:] = -skew(top)
    C[3:, :3] = -skew(top)
    C[3:, 3:] = -skew(bot)
    return C


def coriolis_force(M, nu):
    return coriolis_matrix(M, nu) @ np.asarray(nu, float)


def point_load(F, r):
    """Generalised 6-dof force of a force F applied at r (relative to the CG).

    Returns [F, r x F]. Every point load in the plant goes through this, so no
    moment sign is ever written by hand -- which is how the rudder's roll
    moment came to have the wrong sign while its yaw moment, in the same
    function, had the right one.
    """
    F = np.asarray(F, float)
    return np.concatenate([F, np.cross(np.asarray(r, float), F)])


class Wind:
    """Steady wind on the above-water hull, in surge, sway and yaw.

    `speed` and `direction` are the TRUE wind: where it blows towards, in the
    same earth-fixed convention as the wave directions.
    """

    def __init__(self, speed=0.0, direction=np.pi, L=10.0, freeboard=0.55,
                 beam=2.5, cx=0.7, cy=0.9, x_wind=0.5, rho=RHO_AIR):
        self.speed, self.direction = float(speed), float(direction)
        self.L, self.freeboard, self.beam = L, freeboard, beam
        self.a_lat = L * freeboard              # side projected area
        self.a_front = beam * freeboard         # frontal projected area
        self.cx, self.cy = cx, cy
        # Longitudinal position of the aerodynamic centre of effort, metres
        # forward of the CG. Exposed as a LEVER rather than folded into a C_N
        # coefficient, because the lever is the thing a person can look at a
        # profile drawing and estimate, and its sign decides whether the vessel
        # weathervanes into the wind or away from it. Measured C_N(gamma) curves
        # are not exactly Y times a constant lever -- they peak nearer 40 deg
        # than 90 -- and that shape is what Blendermann's data would supply.
        self.x_wind = x_wind
        self.rho = rho

    @classmethod
    def from_sea_state(cls, hs, direction=np.pi, **kw):
        """Wind speed implied by a fully developed sea: Hs = 0.0248 U^2.

        Pierson-Moskowitz, inverted. It is the honest default for a study that
        specifies a sea state and not a wind: a sea state IS a wind, and taking
        the sea while dropping the wind is a choice, not a neutral omission.
        """
        return cls(speed=float(np.sqrt(max(hs, 0.0) / 0.0248)),
                   direction=direction, **kw)

    def force(self, nu, psi):
        """(X, Y, N) in the body frame, from the apparent wind.

        Signs are fixed by physics, not convention: the force points along the
        apparent wind. Air moving forward past the vessel (gamma near 0) pushes
        it forward; air moving to port pushes it to port.
        """
        if self.speed <= 0.0:
            return 0.0, 0.0, 0.0
        # true wind in the body frame
        wx = self.speed * np.cos(self.direction - psi)
        wy = self.speed * np.sin(self.direction - psi)
        # apparent = true minus the vessel's own velocity. A vessel making
        # 4.5 m/s into an 11 m/s breeze feels 15.5, and that is a factor of two
        # in force -- which is why this is not simply the true wind.
        ax, ay = wx - nu[0], wy - nu[1]
        va2 = ax * ax + ay * ay
        if va2 < 1e-9:
            return 0.0, 0.0, 0.0
        gamma = np.arctan2(ay, ax)     # 0 = blowing from astern, pi = head on
        q = 0.5 * self.rho * va2
        X = q * self.a_front * self.cx * np.cos(gamma)
        Y = q * self.a_lat * self.cy * np.sin(gamma)
        return float(X), float(Y), float(Y * self.x_wind)

    def force6(self, nu, psi, z_cog=0.0):
        """Full 6-dof wind load about the centre of gravity.

        Adds the ROLL moment the 3-dof version leaves out: a beam wind acting
        on the topsides heels the vessel downwind, and the model had no wind
        heel at all. The lateral force is taken to act at the centroid of the
        side area, half the freeboard above the waterline; the moment follows
        from r x F rather than from a hand-written sign.
        """
        X, Y, N = self.force(nu, psi)
        r = np.array([self.x_wind, 0.0, 0.5 * self.freeboard - z_cog])
        K = float(np.cross(r, [X, Y, 0.0])[0])
        return np.array([X, Y, 0.0, K, 0.0, N])


# ------------------------------------------------------ Blendermann (1994)
# Measured wind-load coefficient sets, one per vessel type, from W. Blendermann,
# "Parameter identification of wind loads on ships", J. Wind Eng. Ind. Aerodyn.
# 51 (1994) 339-351. Table and formulas as implemented in Fossen's MSS toolbox,
# LIBRARY/environment/blendermann94.m (MIT licence, copy in data/external/mss).
#
# Columns: CD_t, CD_l_AF at the bow (0), CD_l_AF at the stern (pi), delta, kappa
BLENDERMANN = {
    "car carrier": (0.95, 0.55, 0.60, 0.80, 1.2),
    "cargo vessel, loaded": (0.85, 0.65, 0.55, 0.40, 1.7),
    "cargo vessel, container on deck": (0.85, 0.55, 0.50, 0.40, 1.4),
    "container ship, loaded": (0.90, 0.55, 0.55, 0.40, 1.4),
    "destroyer": (0.85, 0.60, 0.65, 0.65, 1.1),
    "diving support vessel": (0.90, 0.60, 0.80, 0.55, 1.7),
    "drilling vessel": (1.00, 0.85, 0.925, 0.10, 1.7),
    "ferry": (0.90, 0.45, 0.50, 0.80, 1.1),
    "fishing vessel": (0.95, 0.70, 0.70, 0.40, 1.1),
    "lng tanker": (0.70, 0.60, 0.65, 0.50, 1.1),
    "offshore supply vessel": (0.90, 0.55, 0.80, 0.55, 1.2),
    "passenger liner": (0.90, 0.40, 0.40, 0.80, 1.2),
    "research vessel": (0.85, 0.55, 0.65, 0.60, 1.4),
    "speed boat": (0.90, 0.55, 0.60, 0.60, 1.1),
    "tanker, loaded": (0.70, 0.90, 0.55, 0.40, 3.1),
    "tanker, in ballast": (0.70, 0.75, 0.55, 0.40, 2.2),
    "tender": (0.85, 0.55, 0.55, 0.65, 1.1),
}


def blendermann_coefficients(g, vessel, A_F, A_L, s_H, s_L, L_oa):
    """C_X, C_Y, C_K, C_N for a relative-wind angle g in [0, pi], 0 = head wind.

    Two things differ from the MSS source, on purpose, and both are stated
    rather than silently "fixed":

      * MSS's comments describe sH as a horizontal and sL as a vertical
        distance. Its FORMULAS use sH as the height of the lateral-area centroid
        (it multiplies the roll coefficient) and sL as its longitudinal position
        (it sets the yaw lever). The formulas are followed here, the comments
        are not.
      * The yaw formula C_N = (s_L/L - 0.18 (g - pi/2)) C_Y is written for
        0 <= g <= pi. MSS evaluates it at negative angles too, where it is not
        antisymmetric: at g = -pi/2 it gives a lever of s_L/L + 0.57 instead of
        s_L/L. Here g is folded into [0, pi] and the port/starboard sign is
        applied afterwards, which is what the symmetry of a ship requires.
    """
    CD_t, bow, stern, delta, kappa = BLENDERMANN[vessel]
    g = np.clip(np.asarray(g, float), 0.0, np.pi)
    CD_lAF = np.where(g <= np.pi / 2, bow, stern)
    CD_l = CD_lAF * A_F / A_L
    den = 1.0 - 0.5 * delta * (1.0 - CD_l / CD_t) * np.sin(2 * g) ** 2
    CX = -CD_lAF * np.cos(g) / den
    CY = CD_t * np.sin(g) / den
    CK = kappa * (s_H / (A_L / L_oa)) * CY
    CN = (s_L / L_oa - 0.18 * (g - np.pi / 2)) * CY
    return CX, CY, CK, CN


class BlendermannWind:
    """Wind loads from Blendermann's measured coefficients -- hull agnostic.

    Everything specific to a vessel is an input a person can read off a
    general-arrangement drawing: the frontal and lateral projected areas above
    the waterline, the height and longitudinal position of the lateral area's
    centroid, the length overall, and which of the 17 measured vessel types it
    most resembles. For a small USV the matching type is "speed boat".
    """

    def __init__(self, speed=0.0, direction=np.pi, vessel="speed boat",
                 A_F=1.4, A_L=5.5, s_H=0.3, s_L=0.0, L_oa=10.0, rho=RHO_AIR):
        if vessel not in BLENDERMANN:
            raise KeyError(f"unknown vessel type {vessel!r}; one of "
                           f"{sorted(BLENDERMANN)}")
        self.speed, self.direction, self.vessel = float(speed), direction, vessel
        self.A_F, self.A_L, self.s_H, self.s_L = A_F, A_L, s_H, s_L
        self.L_oa, self.rho = L_oa, rho

    @classmethod
    def from_sea_state(cls, hs, direction=np.pi, **kw):
        return cls(speed=float(np.sqrt(max(hs, 0.0) / 0.0248)),
                   direction=direction, **kw)

    def relative(self, nu, psi):
        """Air velocity relative to the vessel, body frame."""
        wx = self.speed * np.cos(self.direction - psi)
        wy = self.speed * np.sin(self.direction - psi)
        return wx - nu[0], wy - nu[1]

    def force6(self, nu, psi, z_cog=0.0):
        """(X, Y, Z, K, M, N) about the centre of gravity.

        The angle g is measured from the bow to where the air comes FROM, so
        g = 0 is a head wind; the lateral force points the way the air moves.
        Moments come from r x F with the centre of pressure placed where
        Blendermann's coefficients put it: longitudinally at s_L shifted by
        -0.18 (g - pi/2) L_oa, vertically at kappa * s_H above the waterline.
        """
        if self.speed <= 0.0:
            return np.zeros(6)
        ax, ay = self.relative(nu, psi)
        va2 = ax * ax + ay * ay
        if va2 < 1e-12:
            return np.zeros(6)
        g = float(np.arctan2(abs(ay), -ax))
        side = 1.0 if ay >= 0.0 else -1.0
        CX, CY, CK, CN = blendermann_coefficients(
            g, self.vessel, self.A_F, self.A_L, self.s_H, self.s_L, self.L_oa)
        q = 0.5 * self.rho * va2
        X = float(q * self.A_F * CX)
        Y = float(side * q * self.A_L * CY)
        x_cp = float((self.s_L / self.L_oa - 0.18 * (g - np.pi / 2))
                     * self.L_oa)
        z_cp = float(CK / max(float(CY), 1e-12) * (self.A_L / self.L_oa))
        F = np.array([X, Y, 0.0])
        M = np.cross([x_cp, 0.0, z_cp - z_cog], F)
        return np.array([X, Y, 0.0, M[0], M[1], M[2]])

    def force(self, nu, psi):
        f = self.force6(nu, psi)
        return float(f[0]), float(f[1]), float(f[5])


# ------------------------------------------------------------------- checks
def test_skew(seed=0, n=200, tol=1e-9):
    """Coriolis forces must do no work, for any mass matrix and any velocity.

    This is the property that makes the construction trustworthy without
    checking the terms one at a time, so it is worth asserting rather than
    assuming: a hand-written expansion that violates it injects or removes
    energy every step, and an integrator will quietly hide that as drift.
    """
    rng = np.random.default_rng(seed)
    worst = 0.0
    for _ in range(n):
        A = rng.normal(size=(6, 6))
        M = A + A.T                             # symmetric, like a mass matrix
        nu = rng.normal(size=6)
        C = coriolis_matrix(M, nu)
        worst = max(worst, float(np.max(np.abs(C + C.T))),
                    abs(float(nu @ C @ nu)))
    assert worst < tol, f"Coriolis matrix is not skew-symmetric: {worst:.3e}"
    return worst


def test_euler(tol=1e-10):
    """Reduce to the textbook result, derived independently here."""
    m, I = 9105.0, np.diag([2588.0, 45912.0, 47787.0])
    M = np.zeros((6, 6))
    M[:3, :3] = m * np.eye(3)
    M[3:, 3:] = I
    nu = np.array([4.5, -0.3, 0.8, 0.05, -0.12, 0.09])
    got = coriolis_force(M, nu)
    v1, v2 = nu[:3], nu[3:]
    want = np.concatenate([m * np.cross(v2, v1), np.cross(v2, I @ v2)])
    err = float(np.max(np.abs(got - want)))
    assert err < tol, f"does not reduce to Euler's equation: {err:.3e}"
    return err


if __name__ == "__main__":
    print(f"  skew-symmetry, 200 random mass matrices : "
          f"worst {test_skew():.2e}")
    print(f"  reduces to m(w x v) and w x (I w)       : "
          f"worst {test_euler():.2e}")
    w = Wind.from_sea_state(3.25)
    print(f"\n  Hs 3.25 m implies {w.speed:.1f} m/s of wind")
    print("  vessel making 4.5 m/s on heading 0\n")
    print(f"  {'wind blows towards':>20}{'V_app':>8}{'X':>9}{'Y':>9}{'N':>9}"
          f"   reading")
    for deg, note in ((0, "from astern, pushes forward"),
                      (45, ""), (90, "on the beam"), (135, ""),
                      (180, "head on, pushes back")):
        w.direction = np.radians(deg)
        nu = np.array([4.5, 0, 0, 0, 0, 0])
        X, Y, N = w.force(nu, 0.0)
        va = np.hypot(w.speed * np.cos(w.direction) - 4.5,
                      w.speed * np.sin(w.direction))
        print(f"  {deg:>16} deg{va:>8.1f}{X:>9.0f}{Y:>9.0f}{N:>9.0f}   {note}")
    nu0 = np.array([4.5, 0, 0, 0, 0, 0])
    w.direction = np.pi
    head = abs(w.force(nu0, 0.0)[0])
    w.direction = np.pi / 2
    beam = abs(w.force(nu0, 0.0)[1])
    print(f"\n  head on, the surge force is {head:.0f} N against a 7000 N "
          f"thrust ({head/7000:.1%});")
    print(f"  on the beam, the side force is {beam:.0f} N.")
